site_name: Business App Name
site_url: https://antonypolitakis.github.io/amazing-website/
repo_url: https://github.com/antonypolitakis/amazing-website
repo_name: amazing-website
edit_uri: project/docs/
nav:
    - 'index.md'
    - 'Arch.md'
    - 'Engineering.md'
    - 'Cyber.md'
theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust

